name: Docker Build
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Image
        run: |
          REPO=${GITHUB_REPOSITORY,,}
          VERSION=${GITHUB_REF_NAME#v}
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t ghcr.io/$REPO:latest \
          -t ghcr.io/$REPO:$VERSION \
          --push .
