name: Docker Build
on:
  push:
    tags:
      - "t*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push Image
        run: |
          REPO=${GITHUB_REPOSITORY,,}
          VERSION=${GITHUB_REF_NAME#}
          docker buildx build \
          --build-arg TAG="${GITHUB_REF#refs/tags/}" \
          --platform linux/amd64,linux/arm64 \
          -t ghcr.io/$REPO:testing \
          -t ghcr.io/$REPO:$VERSION \
          --push .
