name: Release Build
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v4

      - name: Build for Releases
        run: TAG="${GITHUB_REF#refs/tags/}" bash ./release-build.sh

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cbstream-win-amd64.exe
            cbstream-linux-amd64
            cbstream-linux-arm64
            cbstream-apple-amd64
            cbstream-apple-arm64
